### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'endswith'

### ISSUE THREAD

**Issue by xinziming** [cosimo17/QRCodeDetection#2]
File "C:\Users\lenovo\AppData\Roaming\Python\Python36\site-packages\keras\saving\saving_utils.py", line 320, in is_hdf5_filepath
    return (filepath.endswith('.h5') or filepath.endswith('.keras') or
AttributeError: 'NoneType' object has no attribute 'endswith'

**Comment by cosimo17** [comment]
Please provide the full error stack. 
It seems that the filename is None which is not a valid path to save the weights.

**Comment by xinziming** [comment]
Traceback (most recent call last):
  File "D:/bishe/chengxu/QRCodeDetection-master/test.py", line 69, in <module>
    main()
  File "D:/bishe/chengxu/QRCodeDetection-master/test.py", line 54, in main
    model = yolov3(args.shape, anchor_number=len(anchors), weight=args.weight)
  File "D:\bishe\chengxu\QRCodeDetection-master\models\yolov3.py", line 80, in yolov3
    model.load_weights(weight)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python36\site-packages\keras\engine\training.py", line 2329, in load_weights
    filepath, save_format = _detect_save_format(filepath)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python36\site-packages\keras\engine\training.py", line 3008, in _detect_save_format
    if saving_utils.is_hdf5_filepath(filepath):
  File "C:\Users\lenovo\AppData\Roaming\Python\Python36\site-packages\keras\saving\saving_utils.py", line 320, in is_hdf5_filepath
    return (filepath.endswith('.h5') or filepath.endswith('.keras') or
AttributeError: 'NoneType' object has no attribute 'endswith'
Load pretrained weight: None

**Comment by xinziming** [comment]
Thank you. The problem is solved.

**Comment by cosimo17** [comment]
Aha. Glad to see the problem solved.

**Comment by cosimo17** [comment]
I will add some parameter checking to avoid error like this.
